project:
  type: website
  output-dir: _site

website:
  title: "Machine learning with scikit-learn in Python"
  site-url: https://posit-conf-2025.github.io/scikit-learn/

  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Slides"
        contents:
          - materials/slides/classification1.qmd
          - materials/slides/classification2.qmd
          - materials/slides/regression.qmd
          - materials/slides/ensembles.qmd

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    self-contained: true

execute:
  cache: true
  freeze: auto

